package edu.ysu.csis;

public class HeaderPanel extends javax.swing.JPanel {

   
    public HeaderPanel() {
        initComponents();
    }

    public void updateScore(Integer number) {
        this.scoreLabel.setText(number.toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.GridLayout(1, 2));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setText("Score");
        jLabel1.setAlignmentX(5.0F);
        add(jLabel1);

        scoreLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        scoreLabel.setText("0");
        add(scoreLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
