package edu.ysu.csis;

import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;

public class MainFrame extends javax.swing.JFrame implements KeyListener {
    
    public MainFrame() {
        initComponents();
    }
    
    public void start() {
        this.addKeyListener(this);
        this.gamePanel.start();
    }

    public void updatePoints(Integer points) {
        this.headerPanel.updateScore(points);
    }
            
    @Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent keyEvent) {
        switch(keyEvent.getKeyCode()) {
            case KeyEvent.VK_UP:
            case KeyEvent.VK_W:
                this.gamePanel.setPacManDirection(Direction.Up);
                break;
            case KeyEvent.VK_DOWN:
            case KeyEvent.VK_S:
                this.gamePanel.setPacManDirection(Direction.Down);
                break;
            case KeyEvent.VK_RIGHT:
            case KeyEvent.VK_D:
                this.gamePanel.setPacManDirection(Direction.Right);
                break;
            case KeyEvent.VK_LEFT:
            case KeyEvent.VK_A:
                this.gamePanel.setPacManDirection(Direction.Left);
                break;   
        }
    }

    @Override
    public void keyReleased(KeyEvent e) {
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new edu.ysu.csis.HeaderPanel();
        gamePanel = new edu.ysu.csis.GamePanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PacMan");
        setMaximumSize(null);
        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        gamePanel.setPreferredSize(new Dimension(GameSettings.GAME_WIDTH, GameSettings.GAME_HEIGHT));

        javax.swing.GroupLayout gamePanelLayout = new javax.swing.GroupLayout(gamePanel);
        gamePanel.setLayout(gamePanelLayout);
        gamePanelLayout.setHorizontalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );
        gamePanelLayout.setVerticalGroup(
            gamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 898, Short.MAX_VALUE)
        );

        getContentPane().add(gamePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(() -> {
            MainFrame mainFrame = new MainFrame();
            mainFrame.setVisible(true);
            mainFrame.start();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private edu.ysu.csis.GamePanel gamePanel;
    private edu.ysu.csis.HeaderPanel headerPanel;
    // End of variables declaration//GEN-END:variables

}
